### ISSUE TITLE
Error input and view decimal number on Italian localization 

### ISSUE THREAD

**Issue by massimilianochiodi** [tuvakov/compose-vt-decimal-formatter#1]
Hi, I have a problem with your project "compose-vt-decimal-formatter".  In practice, using the field, the comma is seen as a decimal separator, while the thousands separator is always the decimal separator.

Although I tried to pass the data (formatted double) with: format(locale, "%,.2f", amount) I should have seen for example 100.000,55 and not 100.000.55 as in this case.

locale in my case is ITALIAN. 

What I don't understand is that in debug I see the number formatted correctly, while on the phone (Google Pixel 7a) I see the thousands separator equal to the decimal separator.

Can you help me?

**Comment by tuvakov** [comment]
Hi Massimiliano!

I just tested debug and release builds on my Pixel 3A emulator. (API level 34 / Android 14).
Both builds are working fine with Italian locale. Could you share your API level please? So I can test on that one too. 

Additionally, in this project I used `DecimalFormatSymbols` class from JDK under `java.text.*` package.
Android SDK has a class with the same name that does similar thing. Maybe you can try that out too?
Here is the full class name. `android.icu.text.DecimalFormatSymbols`.

**Comment by massimilianochiodi** [comment]
I would like to apologize...
I checked everything, except the main thing... it is called field height; since it was too short, those two/three pixels that showed the rest of the comma were hidden, which I saw as a dot.
I am really very sorry.
However, I hope that no one else has encountered the same problem as me, the solution is trivial.
Thank you anyway for your timely support.

Max
